#!/usr/bin/env bash
#commit
i=1
while [ "$i" -lt 100 ]; do
	if (( i % 15 == 0 )); then

		echo "FizzBuz"
	elif (( i % 3 == 0 )); then
		echo "Fizz"
	elif (( i % 5 == 0 )); then
		echo "Buzz"
	else
		echo "$i"
	fi
	(( i++))
done	
