#!/usr/bin/env bash
#comment
echo "Hour: 0"
i=1
while [ $i -lt 60 ]
do
  echo "$i"
  i=$((i+1))
done
echo "Hour: 1"
a=1
while [ $a -lt 60 ]
do
  echo "$a"
  a=$((a+1))
done
echo "Hour: 2"
b=1
while [ $b -lt 60 ]
do
  echo "$b"
  b=$((b+1))
done
echo "Hour: 3"
c=1
while [ $c -lt 60 ]
do
  echo "$c"
  c=$((c+1))
done
echo "Hour: 4"
d=1
while [ $d -lt 60 ]
do
  echo "$d"
  d=$((d+1))
done
echo "Hour: 5"
e=1
while [ $e -lt 60 ]
do
  echo "$e"
  e=$((e+1))
done
echo "Hour: 6"
f=1
while [ $f -lt 60 ]
do
  echo "$f"
  f=$((f+1))
done
echo "Hour: 7"
g=1
while [ $g -lt 60 ]
do
  echo "$g"
  g=$((g+1))
done
echo "Hour: 8"
h=1
while [ $h -lt 60 ]
do
  echo "$h"
  h=$((h+1))
done
echo "Hour: 9"
s=1
while [ $s -lt 60 ]
do
  echo "$s"
  s=$((s+1))
done
echo "Hour: 10"
z=1
while [ $z -lt 60 ]
do
  echo "$z"
  z=$((z+1))
done
echo "Hour: 11"
y=1
while [ $y -lt 60 ]
do
  echo "$y"
  y=$((y+1))
done
